PreCommit:
  ForbiddenBranches:
    enabled: true
    branch_patterns: ["master", "main"]
  HamlLint:
    enabled: true
    on_warn: fail
    required_executable: bundle
    command: ["bundle", "exec", "haml-lint"]
  RuboCop:
    enabled: true
    on_warn: fail
    required_executable: bundle
    command: ["bundle", "exec", "rubocop"]
  Eslint:
    enabled: true
    required_executable: npm
    command: ["npm", "run", "lint"]
PrePush:
  Brakeman:
    enabled: true
    required_executable: bundle
    command: ["bundle", "exec", "brakeman", "--no-pager"]
