require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - Capfile
    - config.ru
    - '**/*.rb'
  Exclude:
    - bin/**/*
    - config/{environments,initializers}/**/*
    - config/{application,boot,environment,puma,spring}.rb
    - db/**/*
    - node_modules/**/*
  NewCops: enable

Layout/ExtraSpacing:
  Exclude:
    - Gemfile

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/MethodLength:
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/{requests,system}/**/*

RSpec/FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
