AllCops:
  Include:
    - Rakefile
    - Capfile
    - config.ru
  Exclude:
    - bin/**/*
    - db/schema.rb

Layout/ExtraSpacing:
  Exclude:
    - 'Gemfile'

Metrics:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Naming/FileName:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false
