plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Include:
    - Rakefile
    - Capfile
    - config.ru
    - '**/*.rb'
  Exclude:
    - bin/**/*
    - vendor/**/*
    - config/{environments,initializers}/**/*
    - config/{application,boot,environment,puma,spring}.rb
    - db/**/*
    - node_modules/**/*
  NewCops: enable

FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

Metrics/BlockLength:
  AllowedMethods:
    - draw

RSpec/DescribeClass:
  Exclude:
    - spec/{requests,system}/**/*

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
