AllCops:
  Include:
    - Rakefile
    - Capfile
    - config.ru
    - '**/*.rb'
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - db/schema.rb

Layout/ExtraSpacing:
  Exclude:
    - Gemfile

Metrics:
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false
