require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - Capfile
    - config.ru
    - '**/*.rb'
  Exclude:
    - bin/**/*
    - config/{environments,initializers}/**/*
    - config/{application,boot,environment,puma,spring}.rb
    - db/**/*
    - node_modules/**/*
  NewCops: enable

Layout/ExtraSpacing:
  Exclude:
    - Gemfile

Metrics/AbcSize:
  CountRepeatedAttributes: false
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

RSpec/DescribeClass:
  Exclude:
    - spec/{requests,system}/**/*
RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
