require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - Capfile
    - config.ru
    - '**/*.rb'
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
  NewCops: enable

Layout/ExtraSpacing:
  Exclude:
    - Gemfile

Metrics:
  Exclude:
    - db/migrate/*
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
