# frozen_string_literal: true

class NotificationMailer < ApplicationMailer
  def notify(user, subject, document)
    mail(to: user.email, subject:) do |format|
      case document
      when Kramdown::Document
        # HTML is generated by Kramdown, not user controlled
        # rubocop:disable Rails/OutputSafety
        format.html { render layout: 'mailer', locals: { title: subject }, html: document.to_html.html_safe }
        format.text { render layout: 'mailer', plain: document.to_kramdown }
        # rubocop:enable Rails/OutputSafety
      when String
        format.text { render layout: 'mailer', plain: document }
      end
    end
  end
end
