name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  haml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: bundle exec haml-lint
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: npm install
      - run: npm run lint
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: bundle exec rubocop
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: bundle exec brakeman --no-pager
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: moretticamp_test
          POSTGRES_PASSWORD: PG-PASSWORD
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://moretticamp_test:PG-PASSWORD@localhost:5432/moretticamp_test
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: bin/setup
      - run: bin/rails test:prepare
      - run: bundle exec rspec
